language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - MINIKUBE_VERSION=0.28.2
    - HELM_VERSION=2.9.1
    - PATH="$PWD/bin:$PATH"
  matrix:
    - KUBE_VERSION=1.9.4

install:
  - ./ci/install.sh

script:
  - ./ci/test-helm.sh
  - ./ci/test-deploy.sh

notifications:
  slack:
    secure: ropvOzLOI/uYNqKR0Ui/4cv9QU0xh16r4MH5kPPPJazfuuU+SudkB0VAxhWjsV3voYD02vc7VHMHlMKpXIcg8rxdHBLNCPmDuqslPtAAJsbvxpOAEaIvtF92ewa3wBKlX9F6VVWYg6UuhMmrky9/ow1rhF381ZSRKeHfm/fIglYOrg0EI5U8ZP0w7SuQBbpuy5Kq3S6Idxju4UR5j2k3IndCoiuaNRzb4ScX5uxqCft0YQVkmwjPQF00atUWA6YoF9JpYdKdm6IPq6Oma7MZWWtF9UeWr44En8rS5YCw+D7YKdUh4DDbxhSbGMW0uKoVDLXOeW6aeeOvLd6u/zz7kD5vjilOUa3qGJ1lIiDztPW2pNAbpmVdxKPIbbxX7KUKoz8rj/JYM2TVT91LQyYqu60xmmdQQixBn/EO4iVuyIDSge2iZ6QlXPFqyLtaa0o6Q6eFEfL4O8Z3HHh4MT1J3jLnf3QKvarOs6+iocbx6ZagxzLETAEb7TCCY6lN+/Y3RCwWCHM3PgoMMVW6FVQ5FPlka/2QVy8tZT/p09IhDCFvQXSDd2A/5aEQUb6v2tETfz656zKOiBpFbHmDmHQfuZZ/OONnrBPiKja7QlKuJrsY20W2T7cf1B5OUjAiABpdVEjp9jWwuka+MK0cAreuuyg5dLDO5EGO6fE0RDgUf+k=
